package com.autoapplicant.domain.job;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

public record Job(
        UUID id,
        JobSource source,
        String sourceJobId,
        String url,
        String title,
        UUID companyId,
        String companyName,
        String descriptionRaw,
        String descriptionClean,
        EmploymentType employmentType,
        Seniority seniority,
        RemoteType remoteType,
        String location,
        String municipality,
        String region,
        String country,
        Integer salaryMin,
        Integer salaryMax,
        String currency,
        List<String> technologies,
        List<String> skills,
        List<String> languages,
        Instant postedAt,
        Instant scrapedAt,
        String aiSummary,
        List<String> aiTags,
        String aiSeniorityEstimate,
        UUID duplicateGroupId,
        boolean isActive,
        JobCategory jobCategory,
        Instant createdAt,
        Instant updatedAt,
        /** Brief teaser for job cards (1-2 sentences). Populated from RSS or generated by AI. */
        String shortDescription,
        /** When this job was last seen during a crawl. Used for staleness detection. */
        Instant lastSeenAt,
        /** Application deadline stated by the posting. Null when unknown or "ASAP". */
        java.time.LocalDate applicationDeadline
) {}
