package com.autoapplicant.domain.job;

public enum JobCategory {
    SOFTWARE_IT, DATA_ANALYTICS, DESIGN_UX, MARKETING, SALES,
    FINANCE, HR, ENGINEERING, OPERATIONS_LOGISTICS, CUSTOMER_SERVICE,
    LEGAL, HEALTHCARE, MANAGEMENT, EDUCATION, CREATIVE_MEDIA, OTHER
}
