-- The skill taxonomy: reference data every skill is resolved against.
--
-- A skill name is matched here on normalized_name, and the row it lands on supplies the taxonomy
-- link and the category. The category is what decides how a skill is grouped on a CV and whether
-- it counts as a technology, so this list is not decoration — an entry missing here means a real
-- skill arrives uncategorised.
--
-- Categories use the vocabulary the rest of the app expects: Programming Language (never plain
-- "Language", which would be ambiguous with spoken ones), Framework, Library, Database, Cloud,
-- DevOps, Tool, API, AI/ML, Architecture, Testing, Security, Methodology, Domain, Soft Skill.
INSERT INTO skill_taxonomy (name, normalized_name, category, aliases) VALUES
  ('Airflow', 'airflow', 'AI/ML', '{}'),
  ('Apache Spark', 'apache spark', 'AI/ML', '{}'),
  ('Computer Vision', 'computer vision', 'AI/ML', '{}'),
  ('Data Science', 'data science', 'AI/ML', '{}'),
  ('Deep Learning', 'deep learning', 'AI/ML', '{}'),
  ('Feature Engineering', 'feature engineering', 'AI/ML', '{}'),
  ('LLM', 'llm', 'AI/ML', '{}'),
  ('Langchain', 'langchain', 'AI/ML', '{}'),
  ('MLOps', 'mlops', 'AI/ML', '{}'),
  ('Machine Learning', 'machine learning', 'AI/ML', '{}'),
  ('Model Fine-tuning', 'model fine-tuning', 'AI/ML', '{}'),
  ('NLP', 'nlp', 'AI/ML', '{}'),
  ('Ollama', 'ollama', 'AI/ML', '{}'),
  ('OpenAI API', 'openai api', 'AI/ML', '{}'),
  ('Prompt Engineering', 'prompt engineering', 'AI/ML', '{}'),
  ('RAG', 'rag', 'AI/ML', '{}'),
  ('Reinforcement Learning', 'reinforcement learning', 'AI/ML', '{}'),
  ('Vector Embeddings', 'vector embeddings', 'AI/ML', '{}'),
  ('dbt', 'dbt', 'AI/ML', '{}'),
  ('Apache Kafka', 'apache kafka', 'API', '{}'),
  ('Apache Pulsar', 'apache pulsar', 'API', '{}'),
  ('GraphQL', 'graphql', 'API', '{}'),
  ('JWT', 'jwt', 'API', '{}'),
  ('MQTT', 'mqtt', 'API', '{}'),
  ('NATS', 'nats', 'API', '{}'),
  ('OAuth 2.0', 'oauth 2.0', 'API', '{}'),
  ('OpenAPI / Swagger', 'openapi / swagger', 'API', '{}'),
  ('REST', 'rest', 'API', '{}'),
  ('REST API', 'rest api', 'API', '{}'),
  ('RabbitMQ', 'rabbitmq', 'API', '{}'),
  ('SAML', 'saml', 'API', '{}'),
  ('SSE', 'sse', 'API', '{}'),
  ('WebRTC', 'webrtc', 'API', '{}'),
  ('WebSocket', 'websocket', 'API', '{}'),
  ('API Gateway', 'api gateway', 'Architecture', '{}'),
  ('CQRS', 'cqrs', 'Architecture', '{}'),
  ('Clean Architecture', 'clean architecture', 'Architecture', '{}'),
  ('Design Patterns', 'design patterns', 'Architecture', '{}'),
  ('Domain-Driven Design', 'domain-driven design', 'Architecture', '{}'),
  ('Event Sourcing', 'event sourcing', 'Architecture', '{}'),
  ('Event-Driven Architecture', 'event-driven architecture', 'Architecture', '{}'),
  ('Hexagonal Architecture', 'hexagonal architecture', 'Architecture', '{}'),
  ('Microservices', 'microservices', 'Architecture', '{}'),
  ('Modular Monolith', 'modular monolith', 'Architecture', '{}'),
  ('SOLID', 'solid', 'Architecture', '{}'),
  ('Saga Pattern', 'saga pattern', 'Architecture', '{}'),
  ('Serverless', 'serverless', 'Architecture', '{}'),
  ('Service Mesh', 'service mesh', 'Architecture', '{}'),
  ('AWS', 'aws', 'Cloud', '{}'),
  ('AWS CDK', 'aws cdk', 'Cloud', '{}'),
  ('AWS CloudFormation', 'aws cloudformation', 'Cloud', '{}'),
  ('AWS EC2', 'aws ec2', 'Cloud', '{}'),
  ('AWS ECS', 'aws ecs', 'Cloud', '{}'),
  ('AWS EKS', 'aws eks', 'Cloud', '{}'),
  ('AWS Lambda', 'aws lambda', 'Cloud', '{}'),
  ('AWS RDS', 'aws rds', 'Cloud', '{}'),
  ('AWS S3', 'aws s3', 'Cloud', '{}'),
  ('AWS SQS', 'aws sqs', 'Cloud', '{}'),
  ('Azure', 'azure', 'Cloud', '{}'),
  ('Azure AKS', 'azure aks', 'Cloud', '{}'),
  ('Azure DevOps', 'azure devops', 'Cloud', '{}'),
  ('Azure Functions', 'azure functions', 'Cloud', '{}'),
  ('BigQuery', 'bigquery', 'Cloud', '{}'),
  ('Cloudflare', 'cloudflare', 'Cloud', '{}'),
  ('DigitalOcean', 'digitalocean', 'Cloud', '{}'),
  ('Fly.io', 'fly.io', 'Cloud', '{}'),
  ('GCP', 'gcp', 'Cloud', '{}'),
  ('Google Cloud Run', 'google cloud run', 'Cloud', '{}'),
  ('Heroku', 'heroku', 'Cloud', '{}'),
  ('Hetzner', 'hetzner', 'Cloud', '{}'),
  ('Netlify', 'netlify', 'Cloud', '{}'),
  ('Railway', 'railway', 'Cloud', '{}'),
  ('Vercel', 'vercel', 'Cloud', '{}'),
  ('Vertex AI', 'vertex ai', 'Cloud', '{}'),
  ('Apache Cassandra', 'apache cassandra', 'Database', '{}'),
  ('Apache HBase', 'apache hbase', 'Database', '{}'),
  ('ClickHouse', 'clickhouse', 'Database', '{}'),
  ('CockroachDB', 'cockroachdb', 'Database', '{}'),
  ('Couchbase', 'couchbase', 'Database', '{}'),
  ('DynamoDB', 'dynamodb', 'Database', '{}'),
  ('Elasticsearch', 'elasticsearch', 'Database', '{}'),
  ('FaunaDB', 'faunadb', 'Database', '{}'),
  ('Firebase', 'firebase', 'Database', '{}'),
  ('InfluxDB', 'influxdb', 'Database', '{}'),
  ('MariaDB', 'mariadb', 'Database', '{}'),
  ('Microsoft SQL Server', 'microsoft sql server', 'Database', '{}'),
  ('MongoDB', 'mongodb', 'Database', '{}'),
  ('MySQL', 'mysql', 'Database', '{}'),
  ('Neo4j', 'neo4j', 'Database', '{}'),
  ('Oracle Database', 'oracle database', 'Database', '{}'),
  ('Pinecone', 'pinecone', 'Database', '{}'),
  ('PostgreSQL', 'postgresql', 'Database', '{}'),
  ('Qdrant', 'qdrant', 'Database', '{}'),
  ('Redis', 'redis', 'Database', '{}'),
  ('SQLite', 'sqlite', 'Database', '{}'),
  ('Supabase', 'supabase', 'Database', '{}'),
  ('TimescaleDB', 'timescaledb', 'Database', '{}'),
  ('Weaviate', 'weaviate', 'Database', '{}'),
  ('pgvector', 'pgvector', 'Database', '{}'),
  ('Ansible', 'ansible', 'DevOps', '{}'),
  ('ArgoCD', 'argocd', 'DevOps', '{}'),
  ('CI/CD', 'ci/cd', 'DevOps', '{}'),
  ('CircleCI', 'circleci', 'DevOps', '{}'),
  ('Consul', 'consul', 'DevOps', '{}'),
  ('Datadog', 'datadog', 'DevOps', '{}'),
  ('Docker', 'docker', 'DevOps', '{}'),
  ('FluxCD', 'fluxcd', 'DevOps', '{}'),
  ('GitHub Actions', 'github actions', 'DevOps', '{}'),
  ('GitLab CI/CD', 'gitlab ci/cd', 'DevOps', '{}'),
  ('Grafana', 'grafana', 'DevOps', '{}'),
  ('Helm', 'helm', 'DevOps', '{}'),
  ('Istio', 'istio', 'DevOps', '{}'),
  ('Jaeger', 'jaeger', 'DevOps', '{}'),
  ('Jenkins', 'jenkins', 'DevOps', '{}'),
  ('Kubernetes', 'kubernetes', 'DevOps', '{}'),
  ('Loki', 'loki', 'DevOps', '{}'),
  ('New Relic', 'new relic', 'DevOps', '{}'),
  ('Nginx', 'nginx', 'DevOps', '{}'),
  ('OpenTelemetry', 'opentelemetry', 'DevOps', '{}'),
  ('Packer', 'packer', 'DevOps', '{}'),
  ('Prometheus', 'prometheus', 'DevOps', '{}'),
  ('Pulumi', 'pulumi', 'DevOps', '{}'),
  ('Sentry', 'sentry', 'DevOps', '{}'),
  ('Terraform', 'terraform', 'DevOps', '{}'),
  ('Traefik', 'traefik', 'DevOps', '{}'),
  ('Vagrant', 'vagrant', 'DevOps', '{}'),
  ('Vault', 'vault', 'DevOps', '{}'),
  ('Zipkin', 'zipkin', 'DevOps', '{}'),
  ('API Design', 'api design', 'Domain', '{}'),
  ('Backend Development', 'backend development', 'Domain', '{}'),
  ('Blockchain', 'blockchain', 'Domain', '{}'),
  ('Data Engineering', 'data engineering', 'Domain', '{}'),
  ('Database Design', 'database design', 'Domain', '{}'),
  ('E-commerce', 'e-commerce', 'Domain', '{}'),
  ('EdTech', 'edtech', 'Domain', '{}'),
  ('Embedded Systems', 'embedded systems', 'Domain', '{}'),
  ('FinTech', 'fintech', 'Domain', '{}'),
  ('Frontend Development', 'frontend development', 'Domain', '{}'),
  ('Full-Stack Development', 'full-stack development', 'Domain', '{}'),
  ('Game Development', 'game development', 'Domain', '{}'),
  ('HealthTech', 'healthtech', 'Domain', '{}'),
  ('IoT', 'iot', 'Domain', '{}'),
  ('Mobile Development', 'mobile development', 'Domain', '{}'),
  ('Platform Engineering', 'platform engineering', 'Domain', '{}'),
  ('Site Reliability Engineering', 'site reliability engineering', 'Domain', '{}'),
  ('System Design', 'system design', 'Domain', '{}'),
  ('Technical Writing', 'technical writing', 'Domain', '{}'),
  ('.NET', '.net', 'Framework', '{}'),
  ('Actix', 'actix', 'Framework', '{}'),
  ('Angular', 'angular', 'Framework', '{}'),
  ('Astro', 'astro', 'Framework', '{}'),
  ('Axum', 'axum', 'Framework', '{}'),
  ('Bootstrap', 'bootstrap', 'Framework', '{}'),
  ('Django', 'django', 'Framework', '{}'),
  ('Electron', 'electron', 'Framework', '{}'),
  ('Expo', 'expo', 'Framework', '{}'),
  ('Express', 'express', 'Framework', '{}'),
  ('FastAPI', 'fastapi', 'Framework', '{}'),
  ('Fiber', 'fiber', 'Framework', '{}'),
  ('Flask', 'flask', 'Framework', '{}'),
  ('Flutter', 'flutter', 'Framework', '{}'),
  ('Gin', 'gin', 'Framework', '{}'),
  ('Hibernate', 'hibernate', 'Framework', '{}'),
  ('Hono', 'hono', 'Framework', '{}'),
  ('Ktor', 'ktor', 'Framework', '{}'),
  ('Laravel', 'laravel', 'Framework', '{}'),
  ('Micronaut', 'micronaut', 'Framework', '{}'),
  ('NestJS', 'nestjs', 'Framework', '{}'),
  ('Next.js', 'next.js', 'Framework', '{}'),
  ('Node.js', 'node.js', 'Framework', '{}'),
  ('Nuxt.js', 'nuxt.js', 'Framework', '{}'),
  ('Phoenix', 'phoenix', 'Framework', '{}'),
  ('Quarkus', 'quarkus', 'Framework', '{}'),
  ('Qwik', 'qwik', 'Framework', '{}'),
  ('React', 'react', 'Framework', '{}'),
  ('React Native', 'react native', 'Framework', '{}'),
  ('Remix', 'remix', 'Framework', '{}'),
  ('Ruby on Rails', 'ruby on rails', 'Framework', '{}'),
  ('SolidJS', 'solidjs', 'Framework', '{}'),
  ('Spring', 'spring', 'Framework', '{}'),
  ('Spring Boot', 'spring boot', 'Framework', '{}'),
  ('Svelte', 'svelte', 'Framework', '{}'),
  ('SvelteKit', 'sveltekit', 'Framework', '{}'),
  ('Tailwind CSS', 'tailwind css', 'Framework', '{}'),
  ('Vue.js', 'vue.js', 'Framework', '{}'),
  ('tRPC', 'trpc', 'Framework', '{}'),
  ('Axios', 'axios', 'Library', '{}'),
  ('Celery', 'celery', 'Library', '{}'),
  ('Cypress', 'cypress', 'Library', '{}'),
  ('Hugging Face', 'hugging face', 'Library', '{}'),
  ('Jackson', 'jackson', 'Library', '{}'),
  ('Jest', 'jest', 'Library', '{}'),
  ('Keras', 'keras', 'Library', '{}'),
  ('LangChain', 'langchain', 'Library', '{}'),
  ('Lombok', 'lombok', 'Library', '{}'),
  ('Matplotlib', 'matplotlib', 'Library', '{}'),
  ('Mongoose', 'mongoose', 'Library', '{}'),
  ('NLTK', 'nltk', 'Library', '{}'),
  ('NumPy', 'numpy', 'Library', '{}'),
  ('OpenCV', 'opencv', 'Library', '{}'),
  ('Pandas', 'pandas', 'Library', '{}'),
  ('Pinia', 'pinia', 'Library', '{}'),
  ('Playwright', 'playwright', 'Library', '{}'),
  ('Prisma', 'prisma', 'Library', '{}'),
  ('Protocol Buffers', 'protocol buffers', 'Library', '{}'),
  ('Puppeteer', 'puppeteer', 'Library', '{}'),
  ('PyTorch', 'pytorch', 'Library', '{}'),
  ('Pydantic', 'pydantic', 'Library', '{}'),
  ('Redux', 'redux', 'Library', '{}'),
  ('RxJS', 'rxjs', 'Library', '{}'),
  ('SQLAlchemy', 'sqlalchemy', 'Library', '{}'),
  ('Scikit-learn', 'scikit-learn', 'Library', '{}'),
  ('Sequelize', 'sequelize', 'Library', '{}'),
  ('Storybook', 'storybook', 'Library', '{}'),
  ('Tanstack Query', 'tanstack query', 'Library', '{}'),
  ('TensorFlow', 'tensorflow', 'Library', '{}'),
  ('TypeORM', 'typeorm', 'Library', '{}'),
  ('Vitest', 'vitest', 'Library', '{}'),
  ('Zod', 'zod', 'Library', '{}'),
  ('Zustand', 'zustand', 'Library', '{}'),
  ('gRPC', 'grpc', 'Library', '{}'),
  ('spaCy', 'spacy', 'Library', '{}'),
  ('Agile', 'agile', 'Methodology', '{}'),
  ('Code Review', 'code review', 'Methodology', '{}'),
  ('Design Thinking', 'design thinking', 'Methodology', '{}'),
  ('Extreme Programming', 'extreme programming', 'Methodology', '{}'),
  ('Kanban', 'kanban', 'Methodology', '{}'),
  ('Lean', 'lean', 'Methodology', '{}'),
  ('Mob Programming', 'mob programming', 'Methodology', '{}'),
  ('OKRs', 'okrs', 'Methodology', '{}'),
  ('Pair Programming', 'pair programming', 'Methodology', '{}'),
  ('SAFe', 'safe', 'Methodology', '{}'),
  ('Scrum', 'scrum', 'Methodology', '{}'),
  ('Shape Up', 'shape up', 'Methodology', '{}'),
  ('TDD', 'tdd', 'Methodology', '{}'),
  ('ABAP', 'abap', 'Programming Language', '{}'),
  ('Bash', 'bash', 'Programming Language', '{}'),
  ('C#', 'c#', 'Programming Language', '{}'),
  ('C++', 'c++', 'Programming Language', '{}'),
  ('COBOL', 'cobol', 'Programming Language', '{}'),
  ('CSS', 'css', 'Programming Language', '{}'),
  ('Clojure', 'clojure', 'Programming Language', '{}'),
  ('Dart', 'dart', 'Programming Language', '{}'),
  ('Elixir', 'elixir', 'Programming Language', '{}'),
  ('Erlang', 'erlang', 'Programming Language', '{}'),
  ('F#', 'f#', 'Programming Language', '{}'),
  ('Go', 'go', 'Programming Language', '{}'),
  ('Groovy', 'groovy', 'Programming Language', '{}'),
  ('HTML', 'html', 'Programming Language', '{}'),
  ('Haskell', 'haskell', 'Programming Language', '{}'),
  ('Java', 'java', 'Programming Language', '{}'),
  ('JavaScript', 'javascript', 'Programming Language', '{}'),
  ('Julia', 'julia', 'Programming Language', '{}'),
  ('Kotlin', 'kotlin', 'Programming Language', '{}'),
  ('Lua', 'lua', 'Programming Language', '{}'),
  ('MATLAB', 'matlab', 'Programming Language', '{}'),
  ('Objective-C', 'objective-c', 'Programming Language', '{}'),
  ('PHP', 'php', 'Programming Language', '{}'),
  ('PL/SQL', 'pl/sql', 'Programming Language', '{}'),
  ('Perl', 'perl', 'Programming Language', '{}'),
  ('Python', 'python', 'Programming Language', '{}'),
  ('R', 'r', 'Programming Language', '{}'),
  ('Ruby', 'ruby', 'Programming Language', '{}'),
  ('Rust', 'rust', 'Programming Language', '{}'),
  ('SQL', 'sql', 'Programming Language', '{}'),
  ('Scala', 'scala', 'Programming Language', '{}'),
  ('Shell Scripting', 'shell scripting', 'Programming Language', '{}'),
  ('Solidity', 'solidity', 'Programming Language', '{}'),
  ('Swift', 'swift', 'Programming Language', '{}'),
  ('TypeScript', 'typescript', 'Programming Language', '{}'),
  ('WebAssembly', 'webassembly', 'Programming Language', '{}'),
  ('Cryptography', 'cryptography', 'Security', '{}'),
  ('GDPR', 'gdpr', 'Security', '{}'),
  ('ISO 27001', 'iso 27001', 'Security', '{}'),
  ('MFA / 2FA', 'mfa / 2fa', 'Security', '{}'),
  ('OWASP', 'owasp', 'Security', '{}'),
  ('Penetration Testing', 'penetration testing', 'Security', '{}'),
  ('SIEM', 'siem', 'Security', '{}'),
  ('SOC 2', 'soc 2', 'Security', '{}'),
  ('SSO', 'sso', 'Security', '{}'),
  ('TLS / SSL', 'tls / ssl', 'Security', '{}'),
  ('Vulnerability Assessment', 'vulnerability assessment', 'Security', '{}'),
  ('Zero Trust', 'zero trust', 'Security', '{}'),
  ('Adaptability', 'adaptability', 'Soft Skill', '{}'),
  ('Attention to Detail', 'attention to detail', 'Soft Skill', '{}'),
  ('Coaching', 'coaching', 'Soft Skill', '{}'),
  ('Communication', 'communication', 'Soft Skill', '{}'),
  ('Conflict Resolution', 'conflict resolution', 'Soft Skill', '{}'),
  ('Creativity', 'creativity', 'Soft Skill', '{}'),
  ('Critical Thinking', 'critical thinking', 'Soft Skill', '{}'),
  ('Cross-functional Collaboration', 'cross-functional collaboration', 'Soft Skill', '{}'),
  ('Empathy', 'empathy', 'Soft Skill', '{}'),
  ('Leadership', 'leadership', 'Soft Skill', '{}'),
  ('Mentoring', 'mentoring', 'Soft Skill', '{}'),
  ('Negotiation', 'negotiation', 'Soft Skill', '{}'),
  ('Presentation Skills', 'presentation skills', 'Soft Skill', '{}'),
  ('Proactivity', 'proactivity', 'Soft Skill', '{}'),
  ('Problem Solving', 'problem solving', 'Soft Skill', '{}'),
  ('Self-motivation', 'self-motivation', 'Soft Skill', '{}'),
  ('Stakeholder Management', 'stakeholder management', 'Soft Skill', '{}'),
  ('Teamwork', 'teamwork', 'Soft Skill', '{}'),
  ('Time Management', 'time management', 'Soft Skill', '{}'),
  ('Written Communication', 'written communication', 'Soft Skill', '{}'),
  ('BDD', 'bdd', 'Testing', '{}'),
  ('Contract Testing', 'contract testing', 'Testing', '{}'),
  ('End-to-End Testing', 'end-to-end testing', 'Testing', '{}'),
  ('Gatling', 'gatling', 'Testing', '{}'),
  ('Integration Testing', 'integration testing', 'Testing', '{}'),
  ('JUnit', 'junit', 'Testing', '{}'),
  ('Load Testing', 'load testing', 'Testing', '{}'),
  ('Mockito', 'mockito', 'Testing', '{}'),
  ('Performance Testing', 'performance testing', 'Testing', '{}'),
  ('Selenium', 'selenium', 'Testing', '{}'),
  ('Test Automation', 'test automation', 'Testing', '{}'),
  ('Testcontainers', 'testcontainers', 'Testing', '{}'),
  ('Unit Testing', 'unit testing', 'Testing', '{}'),
  ('k6', 'k6', 'Testing', '{}'),
  ('pytest', 'pytest', 'Testing', '{}'),
  ('Bitbucket', 'bitbucket', 'Tool', '{}'),
  ('Confluence', 'confluence', 'Tool', '{}'),
  ('ESLint', 'eslint', 'Tool', '{}'),
  ('Figma', 'figma', 'Tool', '{}'),
  ('Git', 'git', 'Tool', '{}'),
  ('GitHub', 'github', 'Tool', '{}'),
  ('GitLab', 'gitlab', 'Tool', '{}'),
  ('Gradle', 'gradle', 'Tool', '{}'),
  ('Insomnia', 'insomnia', 'Tool', '{}'),
  ('IntelliJ IDEA', 'intellij idea', 'Tool', '{}'),
  ('Jira', 'jira', 'Tool', '{}'),
  ('Linear', 'linear', 'Tool', '{}'),
  ('Linux', 'linux', 'Tool', '{}'),
  ('Makefile', 'makefile', 'Tool', '{}'),
  ('Maven', 'maven', 'Tool', '{}'),
  ('Miro', 'miro', 'Tool', '{}'),
  ('Neovim', 'neovim', 'Tool', '{}'),
  ('Notion', 'notion', 'Tool', '{}'),
  ('Postman', 'postman', 'Tool', '{}'),
  ('Prettier', 'prettier', 'Tool', '{}'),
  ('PyCharm', 'pycharm', 'Tool', '{}'),
  ('SonarQube', 'sonarqube', 'Tool', '{}'),
  ('Swagger', 'swagger', 'Tool', '{}'),
  ('VS Code', 'vs code', 'Tool', '{}'),
  ('Vim', 'vim', 'Tool', '{}'),
  ('Vite', 'vite', 'Tool', '{}'),
  ('WebStorm', 'webstorm', 'Tool', '{}'),
  ('Webpack', 'webpack', 'Tool', '{}'),
  ('Yarn', 'yarn', 'Tool', '{}'),
  ('npm', 'npm', 'Tool', '{}'),
  ('pnpm', 'pnpm', 'Tool', '{}')ON CONFLICT (name) DO NOTHING;
