-- Broad taxonomy expansion: widely-requested skills/technologies missing from V021 + V031, with a
-- deliberate lean toward the Danish/Nordic market this app serves (Umbraco, Optimizely, SAP,
-- Dynamics 365, ITIL, PRINCE2, NIS2, Keycloak, SOAP, and the legacy .NET the local enterprise
-- still runs on). Same rules as V021: display name, lowercased normalized_name, fixed-vocabulary
-- category, curated aliases. ON CONFLICT (name) DO NOTHING keeps re-runs harmless.
--
-- Aliases are kept unambiguous and non-overlapping across rows (SkillCanonicalizer maps each alias
-- to one canonical key), and short/word-like aliases (e.g. "salt", "cd", "ad") are avoided so
-- document keyword scanning does not over-report.

INSERT INTO skill_taxonomy (name, normalized_name, category, aliases) VALUES
  -- Programming languages
  ('PowerShell', 'powershell', 'Programming Language', '{pwsh}'),
  ('Visual Basic .NET', 'visual basic .net', 'Programming Language', '{vb.net,visual basic,vb net}'),
  ('VBA', 'vba', 'Programming Language', '{visual basic for applications}'),
  ('Apex', 'apex', 'Programming Language', '{salesforce apex}'),
  ('Assembly', 'assembly', 'Programming Language', '{assembler}'),
  ('Fortran', 'fortran', 'Programming Language', '{}'),
  ('Delphi', 'delphi', 'Programming Language', '{object pascal}'),

  -- Frameworks
  ('jQuery', 'jquery', 'Framework', '{}'),
  ('Spring MVC', 'spring mvc', 'Framework', '{}'),
  ('Spring WebFlux', 'spring webflux', 'Framework', '{webflux}'),
  ('Spring Cloud', 'spring cloud', 'Framework', '{}'),
  ('Spring Batch', 'spring batch', 'Framework', '{}'),
  ('Vert.x', 'vert.x', 'Framework', '{vertx}'),
  ('Grails', 'grails', 'Framework', '{}'),
  ('JSF', 'jsf', 'Framework', '{jakarta server faces,javaserver faces}'),
  ('Apache Struts', 'apache struts', 'Framework', '{struts}'),
  ('Play Framework', 'play framework', 'Framework', '{}'),
  ('Dropwizard', 'dropwizard', 'Framework', '{}'),
  ('Thymeleaf', 'thymeleaf', 'Framework', '{}'),
  ('Vaadin', 'vaadin', 'Framework', '{}'),
  ('Fastify', 'fastify', 'Framework', '{}'),
  ('Koa', 'koa', 'Framework', '{koa.js}'),
  ('Xamarin', 'xamarin', 'Framework', '{}'),
  ('.NET MAUI', '.net maui', 'Framework', '{maui}'),
  ('Windows Forms', 'windows forms', 'Framework', '{winforms}'),
  ('WCF', 'wcf', 'Framework', '{windows communication foundation}'),
  ('Razor', 'razor', 'Framework', '{razor pages}'),
  ('Ember.js', 'ember.js', 'Framework', '{ember,emberjs}'),
  ('Preact', 'preact', 'Framework', '{}'),
  ('Alpine.js', 'alpine.js', 'Framework', '{alpinejs}'),
  ('Lit', 'lit', 'Framework', '{lit-element}'),
  ('Stimulus', 'stimulus', 'Framework', '{stimulusjs}'),
  ('Backbone.js', 'backbone.js', 'Framework', '{backbone,backbonejs}'),
  ('Gatsby', 'gatsby', 'Framework', '{gatsby.js,gatsbyjs}'),
  ('Ionic', 'ionic', 'Framework', '{}'),
  ('Capacitor', 'capacitor', 'Framework', '{}'),
  ('Apache Cordova', 'apache cordova', 'Framework', '{cordova,phonegap}'),
  ('Qt', 'qt', 'Framework', '{}'),
  ('Unity', 'unity', 'Framework', '{unity3d}'),
  ('Unreal Engine', 'unreal engine', 'Framework', '{unreal,ue4,ue5}'),
  ('Godot', 'godot', 'Framework', '{}'),
  ('Umbraco', 'umbraco', 'Framework', '{}'),
  ('Optimizely', 'optimizely', 'Framework', '{episerver}'),
  ('Sitecore', 'sitecore', 'Framework', '{}'),
  ('Strapi', 'strapi', 'Framework', '{}'),
  ('Contentful', 'contentful', 'Framework', '{}'),
  ('Sanity', 'sanity', 'Framework', '{sanity.io}'),
  ('WordPress', 'wordpress', 'Framework', '{}'),
  ('Drupal', 'drupal', 'Framework', '{}'),
  ('Joomla', 'joomla', 'Framework', '{}'),
  ('Magento', 'magento', 'Framework', '{adobe commerce}'),
  ('Shopify', 'shopify', 'Framework', '{}'),

  -- Libraries
  ('Dapper', 'dapper', 'Library', '{}'),
  ('AutoMapper', 'automapper', 'Library', '{}'),
  ('MediatR', 'mediatr', 'Library', '{}'),
  ('FluentValidation', 'fluentvalidation', 'Library', '{}'),
  ('Serilog', 'serilog', 'Library', '{}'),
  ('NLog', 'nlog', 'Library', '{}'),
  ('Newtonsoft.Json', 'newtonsoft.json', 'Library', '{json.net}'),
  ('Polly', 'polly', 'Library', '{}'),
  ('Log4j', 'log4j', 'Library', '{}'),
  ('SLF4J', 'slf4j', 'Library', '{}'),
  ('Logback', 'logback', 'Library', '{}'),
  ('MapStruct', 'mapstruct', 'Library', '{}'),
  ('Micrometer', 'micrometer', 'Library', '{}'),
  ('Resilience4j', 'resilience4j', 'Library', '{}'),
  ('Feign', 'feign', 'Library', '{openfeign}'),
  ('Redux Toolkit', 'redux toolkit', 'Library', '{rtk}'),
  ('React Hook Form', 'react hook form', 'Library', '{}'),
  ('Formik', 'formik', 'Library', '{}'),
  ('Styled Components', 'styled components', 'Library', '{styled-components}'),
  ('Emotion', 'emotion', 'Library', '{}'),
  ('Framer Motion', 'framer motion', 'Library', '{}'),
  ('D3.js', 'd3.js', 'Library', '{d3,d3js}'),
  ('Three.js', 'three.js', 'Library', '{threejs}'),
  ('Chart.js', 'chart.js', 'Library', '{chartjs}'),
  ('Socket.IO', 'socket.io', 'Library', '{socketio}'),
  ('Lodash', 'lodash', 'Library', '{}'),
  ('SciPy', 'scipy', 'Library', '{}'),
  ('Seaborn', 'seaborn', 'Library', '{}'),
  ('Plotly', 'plotly', 'Library', '{}'),
  ('XGBoost', 'xgboost', 'Library', '{}'),
  ('LightGBM', 'lightgbm', 'Library', '{}'),
  ('JAX', 'jax', 'Library', '{}'),

  -- Databases & data platforms
  ('Snowflake', 'snowflake', 'Database', '{}'),
  ('Databricks', 'databricks', 'Database', '{}'),
  ('Amazon Redshift', 'amazon redshift', 'Database', '{redshift}'),
  ('IBM Db2', 'ibm db2', 'Database', '{db2}'),
  ('Azure Cosmos DB', 'azure cosmos db', 'Database', '{cosmos db,cosmosdb}'),
  ('Apache Solr', 'apache solr', 'Database', '{solr}'),
  ('OpenSearch', 'opensearch', 'Database', '{}'),
  ('Memcached', 'memcached', 'Database', '{}'),
  ('Trino', 'trino', 'Database', '{presto}'),
  ('Apache Hive', 'apache hive', 'Database', '{hive}'),
  ('ChromaDB', 'chromadb', 'Database', '{chroma}'),
  ('Milvus', 'milvus', 'Database', '{}'),
  ('ScyllaDB', 'scylladb', 'Database', '{scylla}'),
  ('Google Bigtable', 'google bigtable', 'Database', '{bigtable}'),
  ('Google Cloud Spanner', 'google cloud spanner', 'Database', '{cloud spanner,spanner}'),

  -- Cloud
  ('AWS CloudWatch', 'aws cloudwatch', 'Cloud', '{cloudwatch}'),
  ('AWS IAM', 'aws iam', 'Cloud', '{}'),
  ('AWS Fargate', 'aws fargate', 'Cloud', '{fargate}'),
  ('AWS SNS', 'aws sns', 'Cloud', '{}'),
  ('AWS Step Functions', 'aws step functions', 'Cloud', '{step functions}'),
  ('AWS Glue', 'aws glue', 'Cloud', '{}'),
  ('AWS Elastic Beanstalk', 'aws elastic beanstalk', 'Cloud', '{elastic beanstalk}'),
  ('AWS CloudFront', 'aws cloudfront', 'Cloud', '{cloudfront}'),
  ('Azure Blob Storage', 'azure blob storage', 'Cloud', '{blob storage}'),
  ('Azure Service Bus', 'azure service bus', 'Cloud', '{}'),
  ('Azure Entra ID', 'azure entra id', 'Cloud', '{entra id,azure ad,azure active directory}'),
  ('Azure App Service', 'azure app service', 'Cloud', '{}'),
  ('GCP Pub/Sub', 'gcp pub/sub', 'Cloud', '{cloud pub/sub}'),
  ('Google Kubernetes Engine', 'google kubernetes engine', 'Cloud', '{gke}'),
  ('Google Cloud Functions', 'google cloud functions', 'Cloud', '{cloud functions}'),
  ('Google Cloud Storage', 'google cloud storage', 'Cloud', '{gcs}'),
  ('Oracle Cloud Infrastructure', 'oracle cloud infrastructure', 'Cloud', '{oci,oracle cloud}'),
  ('OpenStack', 'openstack', 'Cloud', '{}'),
  ('IBM Cloud', 'ibm cloud', 'Cloud', '{}'),
  ('Scaleway', 'scaleway', 'Cloud', '{}'),

  -- DevOps & observability
  ('OpenShift', 'openshift', 'DevOps', '{red hat openshift}'),
  ('Rancher', 'rancher', 'DevOps', '{}'),
  ('Nomad', 'nomad', 'DevOps', '{hashicorp nomad}'),
  ('Chef', 'chef', 'DevOps', '{}'),
  ('Puppet', 'puppet', 'DevOps', '{}'),
  ('SaltStack', 'saltstack', 'DevOps', '{}'),
  ('TeamCity', 'teamcity', 'DevOps', '{}'),
  ('Bamboo', 'bamboo', 'DevOps', '{atlassian bamboo}'),
  ('Travis CI', 'travis ci', 'DevOps', '{travis}'),
  ('Drone CI', 'drone ci', 'DevOps', '{}'),
  ('Spinnaker', 'spinnaker', 'DevOps', '{}'),
  ('Tekton', 'tekton', 'DevOps', '{}'),
  ('Kustomize', 'kustomize', 'DevOps', '{}'),
  ('Skaffold', 'skaffold', 'DevOps', '{}'),
  ('Kibana', 'kibana', 'DevOps', '{}'),
  ('Logstash', 'logstash', 'DevOps', '{}'),
  ('ELK Stack', 'elk stack', 'DevOps', '{elk,elastic stack}'),
  ('Splunk', 'splunk', 'DevOps', '{}'),
  ('Fluentd', 'fluentd', 'DevOps', '{}'),
  ('Graylog', 'graylog', 'DevOps', '{}'),
  ('PagerDuty', 'pagerduty', 'DevOps', '{}'),
  ('Opsgenie', 'opsgenie', 'DevOps', '{}'),
  ('HAProxy', 'haproxy', 'DevOps', '{}'),
  ('Apache HTTP Server', 'apache http server', 'DevOps', '{httpd,apache2}'),
  ('Caddy', 'caddy', 'DevOps', '{}'),
  ('Envoy', 'envoy', 'DevOps', '{envoy proxy}'),
  ('Linkerd', 'linkerd', 'DevOps', '{}'),
  ('Bicep', 'bicep', 'DevOps', '{}'),
  ('Terragrunt', 'terragrunt', 'DevOps', '{}'),

  -- APIs & messaging
  ('SOAP', 'soap', 'API', '{soap web services}'),
  ('OData', 'odata', 'API', '{}'),
  ('OpenID Connect', 'openid connect', 'API', '{oidc}'),
  ('ActiveMQ', 'activemq', 'API', '{apache activemq}'),
  ('ZeroMQ', 'zeromq', 'API', '{zmq}'),
  ('AsyncAPI', 'asyncapi', 'API', '{}'),
  ('JSON-RPC', 'json-rpc', 'API', '{}'),
  ('Kong', 'kong', 'API', '{}'),
  ('Apigee', 'apigee', 'API', '{}'),
  ('WSDL', 'wsdl', 'API', '{}'),
  ('Amazon EventBridge', 'amazon eventbridge', 'API', '{eventbridge}'),

  -- AI / ML
  ('Mistral', 'mistral', 'AI/ML', '{mistral ai}'),
  ('Llama', 'llama', 'AI/ML', '{meta llama}'),
  ('LlamaIndex', 'llamaindex', 'AI/ML', '{llama index}'),
  ('Semantic Kernel', 'semantic kernel', 'AI/ML', '{}'),
  ('AutoGen', 'autogen', 'AI/ML', '{}'),
  ('CrewAI', 'crewai', 'AI/ML', '{}'),
  ('MLflow', 'mlflow', 'AI/ML', '{}'),
  ('Kubeflow', 'kubeflow', 'AI/ML', '{}'),
  ('Weights & Biases', 'weights & biases', 'AI/ML', '{wandb}'),
  ('DVC', 'dvc', 'AI/ML', '{data version control}'),
  ('Ray', 'ray', 'AI/ML', '{}'),
  ('ONNX', 'onnx', 'AI/ML', '{}'),
  ('AWS Bedrock', 'aws bedrock', 'AI/ML', '{bedrock}'),
  ('Azure OpenAI', 'azure openai', 'AI/ML', '{}'),
  ('Amazon SageMaker', 'amazon sagemaker', 'AI/ML', '{sagemaker}'),
  ('Stable Diffusion', 'stable diffusion', 'AI/ML', '{}'),
  ('Whisper', 'whisper', 'AI/ML', '{openai whisper}'),
  ('Recommendation Systems', 'recommendation systems', 'AI/ML', '{recommender systems,recommendation engine}'),
  ('Time Series Forecasting', 'time series forecasting', 'AI/ML', '{time series analysis}'),
  ('Anomaly Detection', 'anomaly detection', 'AI/ML', '{}'),
  ('Sentiment Analysis', 'sentiment analysis', 'AI/ML', '{}'),
  ('OCR', 'ocr', 'AI/ML', '{optical character recognition}'),
  ('Speech Recognition', 'speech recognition', 'AI/ML', '{speech-to-text}'),
  ('GANs', 'gans', 'AI/ML', '{generative adversarial networks}'),
  ('Diffusion Models', 'diffusion models', 'AI/ML', '{}'),
  ('AI Agents', 'ai agents', 'AI/ML', '{agentic ai,autonomous agents}'),

  -- Testing
  ('xUnit', 'xunit', 'Testing', '{xunit.net}'),
  ('NUnit', 'nunit', 'Testing', '{}'),
  ('Moq', 'moq', 'Testing', '{}'),
  ('TestNG', 'testng', 'Testing', '{}'),
  ('Mocha', 'mocha', 'Testing', '{}'),
  ('Chai', 'chai', 'Testing', '{}'),
  ('Jasmine', 'jasmine', 'Testing', '{}'),
  ('Karma', 'karma', 'Testing', '{}'),
  ('React Testing Library', 'react testing library', 'Testing', '{rtl}'),
  ('Enzyme', 'enzyme', 'Testing', '{}'),
  ('WebdriverIO', 'webdriverio', 'Testing', '{wdio}'),
  ('Robot Framework', 'robot framework', 'Testing', '{}'),
  ('Cucumber', 'cucumber', 'Testing', '{}'),
  ('SpecFlow', 'specflow', 'Testing', '{}'),
  ('JMeter', 'jmeter', 'Testing', '{apache jmeter}'),
  ('Locust', 'locust', 'Testing', '{}'),
  ('Pact', 'pact', 'Testing', '{}'),
  ('WireMock', 'wiremock', 'Testing', '{}'),
  ('MockK', 'mockk', 'Testing', '{}'),
  ('Espresso', 'espresso', 'Testing', '{}'),
  ('XCTest', 'xctest', 'Testing', '{}'),
  ('Detox', 'detox', 'Testing', '{}'),
  ('Regression Testing', 'regression testing', 'Testing', '{}'),
  ('Smoke Testing', 'smoke testing', 'Testing', '{}'),
  ('Exploratory Testing', 'exploratory testing', 'Testing', '{}'),
  ('Snapshot Testing', 'snapshot testing', 'Testing', '{}'),
  ('Mutation Testing', 'mutation testing', 'Testing', '{}'),
  ('A/B Testing', 'a/b testing', 'Testing', '{}'),

  -- Security & identity
  ('Keycloak', 'keycloak', 'Security', '{}'),
  ('Auth0', 'auth0', 'Security', '{}'),
  ('Okta', 'okta', 'Security', '{}'),
  ('LDAP', 'ldap', 'Security', '{}'),
  ('Active Directory', 'active directory', 'Security', '{}'),
  ('Kerberos', 'kerberos', 'Security', '{}'),
  ('RBAC', 'rbac', 'Security', '{role-based access control}'),
  ('ABAC', 'abac', 'Security', '{attribute-based access control}'),
  ('PKI', 'pki', 'Security', '{public key infrastructure}'),
  ('SAST', 'sast', 'Security', '{static application security testing}'),
  ('DAST', 'dast', 'Security', '{dynamic application security testing}'),
  ('Snyk', 'snyk', 'Security', '{}'),
  ('Dependabot', 'dependabot', 'Security', '{}'),
  ('Threat Modeling', 'threat modeling', 'Security', '{}'),
  ('PCI DSS', 'pci dss', 'Security', '{pci-dss}'),
  ('HIPAA', 'hipaa', 'Security', '{}'),
  ('NIST', 'nist', 'Security', '{}'),
  ('NIS2', 'nis2', 'Security', '{nis2 directive}'),
  ('CORS', 'cors', 'Security', '{}'),
  ('Content Security Policy', 'content security policy', 'Security', '{csp}'),
  ('Burp Suite', 'burp suite', 'Security', '{}'),
  ('Nmap', 'nmap', 'Security', '{}'),
  ('Metasploit', 'metasploit', 'Security', '{}'),

  -- Methodologies & ways of working
  ('Trunk-Based Development', 'trunk-based development', 'Methodology', '{}'),
  ('GitFlow', 'gitflow', 'Methodology', '{git flow}'),
  ('GitOps', 'gitops', 'Methodology', '{}'),
  ('DevOps', 'devops', 'Methodology', '{}'),
  ('DevSecOps', 'devsecops', 'Methodology', '{}'),
  ('ITIL', 'itil', 'Methodology', '{}'),
  ('PRINCE2', 'prince2', 'Methodology', '{}'),
  ('Rapid Application Development', 'rapid application development', 'Methodology', '{rad}'),
  ('Feature-Driven Development', 'feature-driven development', 'Methodology', '{fdd}'),
  ('Six Sigma', 'six sigma', 'Methodology', '{}'),

  -- Architecture, patterns & systems concepts
  ('Functional Programming', 'functional programming', 'Architecture', '{}'),
  ('Reactive Programming', 'reactive programming', 'Architecture', '{}'),
  ('Actor Model', 'actor model', 'Architecture', '{}'),
  ('Onion Architecture', 'onion architecture', 'Architecture', '{}'),
  ('Backend for Frontend', 'backend for frontend', 'Architecture', '{bff}'),
  ('12-Factor App', '12-factor app', 'Architecture', '{twelve-factor app}'),
  ('Circuit Breaker', 'circuit breaker', 'Architecture', '{}'),
  ('Monorepo', 'monorepo', 'Architecture', '{}'),
  ('Object-Relational Mapping', 'object-relational mapping', 'Architecture', '{orm}'),
  ('Load Balancing', 'load balancing', 'Architecture', '{}'),
  ('Caching', 'caching', 'Architecture', '{}'),

  -- Domains, platforms & business systems
  ('Data Analytics', 'data analytics', 'Domain', '{data analysis}'),
  ('Business Intelligence', 'business intelligence', 'Domain', '{bi}'),
  ('UX/UI Design', 'ux/ui design', 'Domain', '{ux design,ui design}'),
  ('Product Management', 'product management', 'Domain', '{}'),
  ('Quality Assurance', 'quality assurance', 'Domain', '{qa}'),
  ('Cybersecurity', 'cybersecurity', 'Domain', '{}'),
  ('Cloud Engineering', 'cloud engineering', 'Domain', '{}'),
  ('DevOps Engineering', 'devops engineering', 'Domain', '{}'),
  ('Machine Learning Engineering', 'machine learning engineering', 'Domain', '{}'),
  ('AR/VR', 'ar/vr', 'Domain', '{augmented reality,virtual reality,xr}'),
  ('Robotics', 'robotics', 'Domain', '{}'),
  ('ERP', 'erp', 'Domain', '{enterprise resource planning}'),
  ('CRM', 'crm', 'Domain', '{customer relationship management}'),
  ('SAP', 'sap', 'Domain', '{}'),
  ('Salesforce', 'salesforce', 'Domain', '{}'),
  ('Microsoft Dynamics 365', 'microsoft dynamics 365', 'Domain', '{dynamics 365,dynamics crm}'),
  ('Power BI', 'power bi', 'Tool', '{powerbi}'),
  ('Tableau', 'tableau', 'Tool', '{}'),
  ('Looker', 'looker', 'Tool', '{}'),

  -- Tools, IDEs & environments
  ('Subversion', 'subversion', 'Tool', '{svn}'),
  ('Mercurial', 'mercurial', 'Tool', '{hg}'),
  ('Perforce', 'perforce', 'Tool', '{helix core}'),
  ('Eclipse', 'eclipse', 'Tool', '{}'),
  ('NetBeans', 'netbeans', 'Tool', '{}'),
  ('Sublime Text', 'sublime text', 'Tool', '{}'),
  ('Emacs', 'emacs', 'Tool', '{}'),
  ('DBeaver', 'dbeaver', 'Tool', '{}'),
  ('DataGrip', 'datagrip', 'Tool', '{}'),
  ('pgAdmin', 'pgadmin', 'Tool', '{}'),
  ('MySQL Workbench', 'mysql workbench', 'Tool', '{}'),
  ('SQL Server Management Studio', 'sql server management studio', 'Tool', '{ssms}'),
  ('Sourcetree', 'sourcetree', 'Tool', '{}'),
  ('Ant', 'ant', 'Tool', '{apache ant}'),
  ('sbt', 'sbt', 'Tool', '{}'),
  ('Bazel', 'bazel', 'Tool', '{}'),
  ('esbuild', 'esbuild', 'Tool', '{}'),
  ('Babel', 'babel', 'Tool', '{}'),
  ('Rollup', 'rollup', 'Tool', '{rollup.js}'),
  ('Parcel', 'parcel', 'Tool', '{}'),
  ('Nx', 'nx', 'Tool', '{}'),
  ('Turborepo', 'turborepo', 'Tool', '{}'),
  ('Lerna', 'lerna', 'Tool', '{}'),
  ('Slack', 'slack', 'Tool', '{}'),
  ('Microsoft Teams', 'microsoft teams', 'Tool', '{ms teams}'),
  ('Asana', 'asana', 'Tool', '{}'),
  ('draw.io', 'draw.io', 'Tool', '{diagrams.net}'),
  ('Lucidchart', 'lucidchart', 'Tool', '{}'),
  ('Enterprise Architect', 'enterprise architect', 'Tool', '{}'),
  ('Sketch', 'sketch', 'Tool', '{}'),
  ('Adobe XD', 'adobe xd', 'Tool', '{}'),
  ('tmux', 'tmux', 'Tool', '{}')
ON CONFLICT (name) DO NOTHING;

-- Alternate namings folded onto existing rows (matched at compare time by SkillCanonicalizer).
UPDATE skill_taxonomy SET aliases = '{amazon s3,s3}'   WHERE normalized_name = 'aws s3';
UPDATE skill_taxonomy SET aliases = '{amazon ec2,ec2}' WHERE normalized_name = 'aws ec2';
UPDATE skill_taxonomy SET aliases = '{amazon eks,eks}' WHERE normalized_name = 'aws eks';
UPDATE skill_taxonomy SET aliases = '{amazon ecs,ecs}' WHERE normalized_name = 'aws ecs';
UPDATE skill_taxonomy SET aliases = '{amazon rds}'     WHERE normalized_name = 'aws rds';
UPDATE skill_taxonomy SET aliases = '{cloud run}'      WHERE normalized_name = 'google cloud run';
UPDATE skill_taxonomy SET aliases = '{gql}'            WHERE normalized_name = 'graphql';
